### ISSUE TITLE
Support to create virtual cluster with multiple worker node.

### ISSUE THREAD

**Issue by ankurpshah** [loft-sh/virtual-cluster#3]
At present, we can't create a Virtual Cluster that uses more than one worker node. Looking for a feature that allows us to create a virtual cluster with multiple worker nodes. It is nice to have if we can select a worker nodes based on some kind of node affinity.

**Comment by FabianKramm** [comment]
@ankurpshah thanks for opening this issue! Currently the amount of worker nodes per virtual cluster is not restricted and not limited to one. The way it works is like this:
- The virtual cluster has no scheduler and syncs pods usually unmodified to the host namespace (just creates them there)
- The host kubernetes scheduler assigns the pod a node (this can be any node that is available in the host cluster and allowed in the namespace)
- As soon as the virtual cluster sees what node the pod got assigned it creates a node object in the virtual cluster (or removes a node if it is not used at least by 1 pod)
- In the beginning this looks like there is only one node available in the virtual cluster because there is only 1 pod assigned to 1 node. If there would be 2 pods assigned to 2 different nodes then in the virtual cluster 2 nodes would be present.

There is currently an option called `--sync-all-nodes` that can be used with `--fake-nodes=false` which will by default sync all nodes to the virtual cluster. 

It really depends now on your use case on what to do:
1. If you need to start all pods that are running in the virtual cluster to specific nodes this can be accomplished by simply mutating the pods that are created by the virtual cluster via an admission controller (e.g. [kyverno](https://github.com/kyverno/kyverno) or [PodNodeSelector](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector)) to use the specific nodes you want (no change to the virtual cluster is needed, this would work right away)
2. If you need those nodes present at all time in the virtual cluster (e.g. for creating pods directly on them via a DaemonSet) then we would need to add a flag to the virtual cluster that would accept a node selector (node affinity is not really possible in this case) which would be used to sync all these nodes to the virtual cluster.
